#include "headers/localization.h"
#include <map>

Language currentLanguage = LANG_EN;

std::map<std::string, std::map<Language, std::string>> dictionary = {
    // Menu Options
    {"MENU_TITLE",
     {{LANG_ES, "PROYECTO CONFIDENCIAL"}, {LANG_EN, "CONFIDENTIAL PROJECT"}}},
    {"MENU_SUBTITLE",
     {{LANG_ES, "LABORATORIO DE CONTENCION"}, {LANG_EN, "CONTAINMENT LAB"}}},
    {"MENU_SUBTITLE_AUDIO",
     {{LANG_ES, "AJUSTES DE AUDIO"}, {LANG_EN, "AUDIO SETTINGS"}}},
    {"MENU_START", {{LANG_ES, "INICIAR JUEGO"}, {LANG_EN, "START GAME"}}},
    {"MENU_OPTIONS", {{LANG_ES, "OPCIONES"}, {LANG_EN, "OPTIONS"}}},
    {"MENU_CONTROLS", {{LANG_ES, "CONTROLES"}, {LANG_EN, "CONTROLS"}}},
    {"CTRL_W", {{LANG_ES, "W - Avanzar"}, {LANG_EN, "W - Move Forward"}}},
    {"CTRL_S", {{LANG_ES, "S - Retroceder"}, {LANG_EN, "S - Move Backward"}}},
    {"CTRL_A",
     {{LANG_ES, "A - Mover a la izquierda"}, {LANG_EN, "A - Move Left"}}},
    {"CTRL_D",
     {{LANG_ES, "D - Mover a la derecha"}, {LANG_EN, "D - Move Right"}}},
    {"CTRL_Q", {{LANG_ES, "Q - Cambiar Arma"}, {LANG_EN, "Q - Cycle Weapon"}}},
    {"CTRL_R", {{LANG_ES, "R - Recargar"}, {LANG_EN, "R - Reload Weapon"}}},
    {"CTRL_E", {{LANG_ES, "E - Interactuar"}, {LANG_EN, "E - Interact"}}},
    {"CTRL_F", {{LANG_ES, "F - Linterna"}, {LANG_EN, "F - Flashlight"}}},
    {"CTRL_Z", {{LANG_ES, "Z - Usar interruptor"}, {LANG_EN, "Z - Use switch"}}},
    {"CTRL_SHIFT", {{LANG_ES, "SHIFT - Correr"}, {LANG_EN, "SHIFT - Sprint"}}},
    {"MENU_CREDITS", {{LANG_ES, "CREDITOS"}, {LANG_EN, "CREDITS"}}},
    {"CREDITS_TITLE",
     {{LANG_ES, "DESARROLLADO POR:"}, {LANG_EN, "DEVELOPED BY:"}}},
    {"CREDITS_DEV_1",
     {{LANG_ES, "- Francisco Ruiz"}, {LANG_EN, "- Francisco Ruiz"}}},
    {"CREDITS_DEV_2",
     {{LANG_ES, "- Rutsammy Acevedo"}, {LANG_EN, "- Rutsammy Acevedo"}}},
    {"CREDITS_DEV_3",
     {{LANG_ES, "- Jair Narvaez"}, {LANG_EN, "- Jair Narvaez"}}},
    {"CREDITS_DEV_4",
     {{LANG_ES, "- Christiam Reyes"}, {LANG_EN, "- Christiam Reyes"}}},
    {"CREDITS_TUTOR_TITLE", {{LANG_ES, "TUTOR:"}, {LANG_EN, "TUTOR:"}}},
    {"CREDITS_TUTOR",
     {{LANG_ES, "- Danny Chavéz"}, {LANG_EN, "- Danny Chavéz"}}},
    {"MENU_EXIT", {{LANG_ES, "SALIR"}, {LANG_EN, "EXIT"}}},
    {"MENU_HINT_BACK",
     {{LANG_ES, "PRESIONE VOLVER PARA IR AL MENU PRINCIPAL"},
      {LANG_EN, "PRESS BACK TO RETURN TO MAIN MENU"}}},
    {"MENU_HINT_START",
     {{LANG_ES, "ENTER / ESPACIO tambien inicia"},
      {LANG_EN, "ENTER / SPACE also starts"}}},
    {"MENU_MUTE_ACTIVE",
     {{LANG_ES, "QUITAR SONIDO (MUTE) [ACTIVO]"},
      {LANG_EN, "MUTE AUDIO [ACTIVE]"}}},
    {"MENU_MUTE", {{LANG_ES, "QUITAR SONIDO (MUTE)"}, {LANG_EN, "MUTE AUDIO"}}},
    {"MENU_UNMUTE_ACTIVE",
     {{LANG_ES, "ACTIVAR SONIDO [ACTIVO]"},
      {LANG_EN, "ENABLE AUDIO [ACTIVE]"}}},
    {"MENU_UNMUTE", {{LANG_ES, "ACTIVAR SONIDO"}, {LANG_EN, "ENABLE AUDIO"}}},
    {"MENU_BACK", {{LANG_ES, "VOLVER"}, {LANG_EN, "BACK"}}},
    {"MENU_LANG_ES", {{LANG_ES, "ESPANOL [ACTIVO]"}, {LANG_EN, "SPANISH"}}},
    {"MENU_LANG_ES_INACTIVE", {{LANG_ES, "ESPANOL"}, {LANG_EN, "SPANISH"}}},
    {"MENU_LANG_EN", {{LANG_ES, "INGLES"}, {LANG_EN, "ENGLISH [ACTIVE]"}}},
    {"MENU_LANG_EN_INACTIVE", {{LANG_ES, "INGLES"}, {LANG_EN, "ENGLISH"}}},

    // Gameplay Intro
    {"INTRO_1",
     {{LANG_ES, "========================================================="},
      {LANG_EN, "========================================================="}}},
    {"INTRO_2",
     {{LANG_ES, "               PROYECTO CONFIDENCIAL - REINICIO          "},
      {LANG_EN, "               CONFIDENTIAL PROJECT - REBOOT             "}}},
    {"INTRO_3",
     {{LANG_ES, "El entorno es silencioso y vacio."},
      {LANG_EN, "The environment is silent and empty."}}},
    {"INTRO_4",
     {{LANG_ES, "Moverte: W A S D  | Mirar: MOUSE | Sprint: SHIFT"},
      {LANG_EN, "Move: W A S D  | Look: MOUSE | Sprint: SHIFT"}}},
    {"INTRO_5",
     {{LANG_ES, "Interactuar/Abrir Puertas: E | Linterna: F"},
      {LANG_EN, "Interact/Open Doors: E | Flashlight: F"}}},
    {"INTRO_6",
     {{LANG_ES,
       "Busca TARJETAS DE ACCESO para avanzar a las siguientes salas."},
      {LANG_EN, "Find ACCESS CARDS to advance to the next rooms."}}},

    // System Down
    {"SYSTEM_DOWN_1",
     {{LANG_ES, "               SISTEMA CAIDO - REINICIO IMPOSIBLE        "},
      {LANG_EN, "               SYSTEM DOWN - REBOOT IMPOSSIBLE           "}}},
    {"HINT_ESC_EXIT",
     {{LANG_ES, "Presiona ESC para salir."}, {LANG_EN, "Press ESC to exit."}}},
    {"CONSOLE_REACTIVATED",
     {{LANG_ES, "[SISTEMA REACTIVADO]... INICIANDO SECUENCIA DE COPIA."},
      {LANG_EN, "[SYSTEM REACTIVATED]... INITIATING COPY SEQUENCE."}}},
    {"CONSOLE_WARNING_COPY",
     {{LANG_ES, "[ADVERTENCIA]... ANOMALIA DETECTADA EN LA REPLICACION."},
      {LANG_EN, "[WARNING]... ANOMALY DETECTED IN REPLICATION."}}},
    {"CONSOLE_DISTORTION",
     {{LANG_ES,
       "El entorno pierde estabilidad. Los objetos empiezan a flotar."},
      {LANG_EN, "The environment loses stability. Objects begin to float."}}},
    {"CONSOLE_MISSING_BATS",
     {{LANG_ES, "\n[CONSOLA]: Energia principal fuera de linea. Faltan "},
      {LANG_EN, "\n[CONSOLE]: Main power offline. Missing "}}},
    {"CONSOLE_BATS_WORD",
     {{LANG_ES, " Baterias.\n"}, {LANG_EN, " Batteries.\n"}}},
    {"CONSOLE_BAT_COLLECTED",
     {{LANG_ES, "\n[BATERIA RECOLECTADA]: Tienes "},
      {LANG_EN, "\n[BATTERY COLLECTED]: You have "}}},
    {"CONSOLE_EXHAUSTED",
     {{LANG_ES, "\n[AGITADO]: Te has quedado sin aliento.\n"},
      {LANG_EN, "\n[EXHAUSTED]: You have run out of breath.\n"}}},

    // Typewriter
    {"TYPE_SCENE_1",
     {{LANG_ES, "ESCENA 1: PASILLO DE ACCESO"},
      {LANG_EN, "SCENE 1: ACCESS CORRIDOR"}}},
    {"TYPE_SCENE_2",
     {{LANG_ES, "ESCENA 2: SALA DE CONTROL \nLuz verde tenue. "},
      {LANG_EN, "SCENE 2: CONTROL ROOM \nDim green light. "}}},
    {"TYPE_SCENE_3",
     {{LANG_ES, "ESCENA 3: LABORATORIO PRINCIPAL\nEncuentras la esfera "},
      {LANG_EN, "SCENE 3: MAIN LABORATORY\nYou find the sphere "}}},
    {"TYPE_SCENE_4_5",
     {{LANG_ES, "ESCENA 4 & 5: ACTIVACION Y DISTORSION DE LA REALIDAD"},
      {LANG_EN, "SCENE 4 & 5: ACTIVATION AND REALITY DISTORTION"}}},
    {"TYPE_PANEL_INIT",
     {{LANG_ES, "[SISTEMA]: Inicializando panel de alineacion de simbolos."},
      {LANG_EN, "[SYSTEM]: Initializing symbol alignment panel."}}},
    {"TYPE_PANEL_SOLVED",
     {{LANG_ES, "[SISTEMA]: Resolviendo panel. Camara estatica automatica."},
      {LANG_EN, "[SYSTEM]: Solving panel. Automatic static camera."}}},
    {"TYPE_YELLOW_ACCEPTED",
     {{LANG_ES, "[PUERTA]: Tarjeta Amarilla Aceptada. Accediendo a Sala "},
      {LANG_EN, "[DOOR]: Yellow Card Accepted. Accessing Room "}}},
    {"TYPE_RED_ACCEPTED",
     {{LANG_ES, "[PUERTA]: Tarjeta Roja Aceptada. Peligro: Zona de "},
      {LANG_EN, "[DOOR]: Red Card Accepted. Warning: Zone of "}}},
    {"TYPE_BLUE_ACCEPTED",
     {{LANG_ES, "[PUERTA]: Tarjeta Azul Aceptada. Acceso concedido."},
      {LANG_EN, "[DOOR]: Blue Card Accepted. Access granted."}}},
    {"TYPE_NOT_COPY",
     {{LANG_ES, "NO ES UNA COPIA... ESTA APRENDIENDO. CORRE."},
      {LANG_EN, "IT IS NOT A COPY... IT IS LEARNING. RUN."}}},
    {"TYPE_DRAWER_STUCK",
     {{LANG_ES, "[CAJON]: Esta vacio o atascado."},
      {LANG_EN, "[DRAWER]: It is empty or stuck."}}},
    {"TYPE_SCENE_9",
     {{LANG_ES, "ESCENA 9: FALLO TOTAL"}, {LANG_EN, "SCENE 9: TOTAL FAILURE"}}},
    {"TYPE_COPY_COMPLETE",
     {{LANG_ES, "COPIA COMPLETA. HAS SIDO REEMPLAZADO."},
      {LANG_EN, "COPY COMPLETE. YOU HAVE BEEN REPLACED."}}},
    {"TYPE_BLACK_DOOR",
     {{LANG_ES, "[PUERTA NEGRA]: Acceso concedido."},
      {LANG_EN, "[BLACK DOOR]: Access granted."}}},
    {"TYPE_DOOR_OPEN",
     {{LANG_ES, "[PUERTA]: Abierta."}, {LANG_EN, "[DOOR]: Opened."}}},
    {"TYPE_DOOR_LOCKED_YELLOW",
     {{LANG_ES, "[PUERTA BLOQUEADA]: Se requiere Tarjeta Amarilla."},
      {LANG_EN, "[LOCKED DOOR]: Yellow Card required."}}},
    {"TYPE_DOOR_LOCKED_RED",
     {{LANG_ES, "[PUERTA BLOQUEADA]: Se requiere Tarjeta Roja."},
      {LANG_EN, "[LOCKED DOOR]: Red Card required."}}},
    {"TYPE_DOOR_LOCKED_BLUE",
     {{LANG_ES, "[PUERTA BLOQUEADA]: Se requiere Tarjeta Azul."},
      {LANG_EN, "[LOCKED DOOR]: Blue Card required."}}},
    {"TYPE_BLOOD_TRAIL",
     {{LANG_ES, "[SANGRE]: Alguien estuvo perdiendo mucha sangre por aqui..."},
      {LANG_EN, "[BLOOD]: Someone was losing a lot of blood around here..."}}},

    // Minigames ImGui
    {"MINIGAME_WIRE_TITLE",
     {{LANG_ES, "PANEL DE CONEXION DE CABLES"},
      {LANG_EN, "WIRE CONNECTION PANEL"}}},
    {"MINIGAME_WIRE_HINT",
     {{LANG_ES, "Conecta los terminales del mismo color."},
      {LANG_EN, "Connect the terminals of the same color."}}},
    {"MINIGAME_SYMBOL_TITLE",
     {{LANG_ES, "ALINEACION DE SIMBOLOS"}, {LANG_EN, "SYMBOL ALIGNMENT"}}},
    {"MINIGAME_SYMBOL_HINT",
     {{LANG_ES, "Alinea todos los simbolos a '%s' para abrir la puerta."},
      {LANG_EN, "Align all symbols to '%s' to open the door."}}},
    {"MINIGAME_SYMBOL_WHEEL", {{LANG_ES, "Rueda"}, {LANG_EN, "Wheel"}}},
    {"MINIGAME_ACCESS_GRANTED",
     {{LANG_ES, "ACCESO AUTORIZADO"}, {LANG_EN, "ACCESS GRANTED"}}},
    {"MINIGAME_SYSTEM_LOCKED",
     {{LANG_ES, "SISTEMA BLOQUEADO"}, {LANG_EN, "SYSTEM LOCKED"}}},

    // Entity Interactions
    {"ENTITY_WIRE",
     {{LANG_ES, "[CABLE SUELTO]: Hay un cable pelado aqui."},
      {LANG_EN, "[LOOSE WIRE]: There is an exposed wire here."}}},
    {"ENTITY_LOG1",
     {{LANG_ES,
       "LOG 1 (Arrugado): 'Apagon general. Las compuertas se bloquearon.'"},
      {LANG_EN,
       "LOG 1 (Crumpled): 'General blackout. The airlocks were locked.'"}}},
    {"ENTITY_MONITOR_AUX",
     {{LANG_ES, "[MONITOR AUXILIAR]: 'Sistema inestable.'"},
      {LANG_EN, "[AUX MONITOR]: 'Unstable system.'"}}},
    {"ENTITY_ERROR_SCREEN",
     {{LANG_ES, "[PANTALLA ERROR]: 'Falla de contencion.'"},
      {LANG_EN, "[ERROR SCREEN]: 'Containment failure.'"}}},
    {"ENTITY_MACHINE",
     {{LANG_ES, "[MAQUINA]: Unidad Frigorifica."},
      {LANG_EN, "[MACHINE]: Refrigeration Unit."}}},
    {"ENTITY_LOG2",
     {{LANG_ES, "LOG 2 (Sangriento): 'La muestra escapo.'"},
      {LANG_EN, "LOG 2 (Bloody): 'The specimen escaped.'"}}},
    {"ENTITY_STAIN",
     {{LANG_ES, "[MANCHA]: Rastro oscuro hacia ventilacion."},
      {LANG_EN, "[STAIN]: Dark trail towards ventilation."}}},

    // Cards & Docs
    {"DOC_YELLOW", {{LANG_ES, "TARJETA AMARILLA"}, {LANG_EN, "YELLOW CARD"}}},
    {"DOC_RED", {{LANG_ES, "TARJETA ROJA"}, {LANG_EN, "RED CARD"}}},
    {"DOC_BLUE", {{LANG_ES, "TARJETA AZUL"}, {LANG_EN, "BLUE CARD"}}},
    {"DOC_BODY_YELLOW",
     {{LANG_ES,
       "Nivel de Acceso: 1\nSector: Pruebas Iniciales\n\nNotas: El sujeto "
       "muestra hiperactividad celular. No acercarse sin traje de proteccion."},
      {LANG_EN,
       "Access Level: 1\nSector: Initial Tests\n\nNotes: Subject shows "
       "cellular hyperactivity. Do not approach without hazmat suit."}}},
    {"DOC_BODY_RED",
     {{LANG_ES, "Nivel de Acceso: 2\nSector: Contencion\n\nNotas: INCIDENTE 04 "
                "- Ruptura de capsula B. Personal de seguridad no responde."},
      {LANG_EN, "Access Level: 2\nSector: Containment\n\nNotes: INCIDENT 04 - "
                "Capsule B breach. Security personnel unresponsive."}}},
    {"DOC_BODY_BLUE",
     {{LANG_ES, "Nivel de Acceso: 3\nSector: Administracion\n\nNotas: Evacuar "
                "de inmediato. Destruir los discos duros."},
      {LANG_EN, "Access Level: 3\nSector: Administration\n\nNotes: Evacuate "
                "immediately. Destroy hard drives."}}},

    // Inventory and UI
    {"DOC_CLOSE_HINT",
     {{LANG_ES, "E o ESC para cerrar"}, {LANG_EN, "E or ESC to close"}}},
    {"INV_FLASHLIGHT_ON",
     {{LANG_ES, "[F] LINTERNA ON"}, {LANG_EN, "[F] LIGHT ON"}}},
    {"INV_FLASHLIGHT_OFF",
     {{LANG_ES, "[F] LINTERNA OFF"}, {LANG_EN, "[F] LIGHT OFF"}}},
    {"INV_KEY_YELLOW", {{LANG_ES, "T.Amarilla"}, {LANG_EN, "Y.Card"}}},
    {"INV_KEY_RED", {{LANG_ES, "T.Roja"}, {LANG_EN, "R.Card"}}},
    {"INV_KEY_BLUE", {{LANG_ES, "T.Azul"}, {LANG_EN, "B.Card"}}},
    {"INV_BATS", {{LANG_ES, "Bats:%d/3"}, {LANG_EN, "Bats:%d/3"}}},

    // Entities and combat
    {"[COMBATE]: cerdo eliminada.",
     {{LANG_ES, "[COMBATE]: Cerdo eliminado."},
      {LANG_EN, "[COMBAT]: Pig eliminated."}}},
    {"[COMBATE]: esqueleto eliminada.",
     {{LANG_ES, "[COMBATE]: Esqueleto eliminado."},
      {LANG_EN, "[COMBAT]: Skeleton eliminated."}}},
    {"[RUIDO]: El esqueleto se sobresalta...",
     {{LANG_ES, "[RUIDO]: El esqueleto se sobresalta..."},
      {LANG_EN, "[NOISE]: The skeleton is startled..."}}},

    // Game Over and Victory Screens
    {"GAMEOVER_TITLE", {{LANG_ES, "FIN DEL JUEGO"}, {LANG_EN, "GAME OVER"}}},
    {"GAMEOVER_DESC",
     {{LANG_ES, "El tiempo se agoto. La oscuridad te ha consumido."},
      {LANG_EN, "Time ran out. The darkness has consumed you."}}},
    {"VICTORY_TITLE",
     {{LANG_ES, "MISION COMPLETADA"}, {LANG_EN, "MISSION COMPLETED"}}},
    {"VICTORY_DESC",
     {{LANG_ES,
       "La energia principal del laboratorio ha sido restablecida. Sistemas de "
       "contencion estables. Sistema de ventilacion reanudado."},
      {LANG_EN, "Main laboratory power has been restored. Containment systems "
                "stable. Ventilation system resumed."}}},
    {"BTN_EXIT", {{LANG_ES, "SALIR DEL JUEGO"}, {LANG_EN, "EXIT GAME"}}},
    {"BTN_MAIN_MENU", {{LANG_ES, "MENU PRINCIPAL"}, {LANG_EN, "MAIN MENU"}}},

    {"INV_ENERGY", {{LANG_ES, "Energia"}, {LANG_EN, "Energy"}}},

    // Switches and Panels
    {"HINT_INTERACT_SWITCH",
     {{LANG_ES, "Presiona Z para interactuar con el interruptor"},
      {LANG_EN, "Press Z to interact with the switch"}}},
    {"SWITCH_ACTIVATED",
     {{LANG_ES, "Interruptor activado."}, {LANG_EN, "Switch activated."}}},
    {"ENERGY_RESTORED",
     {{LANG_ES, "¡Energia principal restablecida!"},
      {LANG_EN, "Main energy restored!"}}},
    {"TIME_OUT_VENT",
     {{LANG_ES, "El tiempo se ha agotado. El sistema de ventilacion fallo."},
      {LANG_EN, "Time ran out. The ventilation system failed."}}},

    // Switch Panel ImGui
    {"PANEL_TITLE_EMERGENCY",
     {{LANG_ES, "Panel Electrico de Emergencia"},
      {LANG_EN, "Emergency Electrical Panel"}}},
    {"PANEL_STATUS_ONLINE",
     {{LANG_ES, "Estado: EN LINEA"}, {LANG_EN, "Status: ONLINE"}}},
    {"PANEL_STATUS_OFFLINE",
     {{LANG_ES, "Estado: DESCONECTADO"}, {LANG_EN, "Status: OFFLINE"}}},
    {"PANEL_PULL_LEVER",
     {{LANG_ES, "Baja la palanca para restablecer:"},
      {LANG_EN, "Pull the lever to restore:"}}},
    {"PANEL_LEVER", {{LANG_ES, "Palanca"}, {LANG_EN, "Lever"}}},
    {"BTN_CLOSE", {{LANG_ES, "Cerrar"}, {LANG_EN, "Close"}}},
    {"SWITCH_ARCHIVE",
     {{LANG_ES, "Interruptor: Archivo"}, {LANG_EN, "Switch: Archive"}}},
    {"SWITCH_LAB",
     {{LANG_ES, "Interruptor: Laboratorio"}, {LANG_EN, "Switch: Laboratory"}}},
    {"SWITCH_ELEVATOR",
     {{LANG_ES, "Interruptor: Ascensor"}, {LANG_EN, "Switch: Elevator"}}},

    {"", {{LANG_ES, ""}, {LANG_EN, ""}}}};

const char *getText(const std::string &key) {
  auto it = dictionary.find(key);
  if (it != dictionary.end()) {
    return it->second[currentLanguage].c_str();
  }
  return key.c_str(); // Fallback
}
